language: python
python:
  - "3.5"
  - "3.6"

# Python 3.7 has to be done a different way
# https://github.com/travis-ci/travis-ci/issues/9069
jobs:
  include:
    - language: python
      python: "3.7"
      dist: xenial
      sudo: required

# Allow some newer versions of Python to fail for now
# This will be changed once the required packages starts
# supporting the newer versions of Python:
#matrix:
#  fast_finish: true
#  allow_failures:
#    - python: "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest
branches:
  only:
    - master
    - devel